steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/carfeeling-api', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/carfeeling-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'carfeeling-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/carfeeling-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'southamerica-east1'
      - '--allow-unauthenticated' 